name: README build

on:
  push:
    branches:
      - main
  schedule:
    - cron: '* * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current repository to Main branch
        uses: actions/checkout@v2
      - name: Setup NodeJs 14.x
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Cache dependencies and build outputs to improve workflow execution time.
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.os }}-js-${{ hashFiles('package-lock.json') }}
      - name: Install dependencies
        run: npm install
      - name: Generate README file
        run: node index.js
      - name: Commit adn push
        run: |
            git commit README.md -m 'Re-build README.Rmd' || echo "No changes to commit"
            git push origin || echo "No changes to commit"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}