name: README build

on:
  push:
    branches:
      - main
  schedule:
    - cron: '* * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current repository to Main branch
        uses: actions/checkout
      - name: Setup NodeJs 14.x
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Cache dependencies and build outputs to improve workflow execution time.
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.os }}-js-${{ hashFiles('package-lock.json') }}
      - name: Install dependencies
        run: npm install
      - name: Generate README file
        run: node index.js
      - name: Commit files
        run: git commit -m "Create new Readme by Git Action" -a
      - name: Push changes
        uses: estebandlp/estebandlp
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}